baseURL = 'chromoton.org'
languageCode = 'en-us'
title = "Chromoton's Blog"
theme = 'nightfall'

[params]
author = "Daniel Harrer"
user = "chromotron"
hostname = "github.io"

[[params.social]]
key = 0
name = "github"
url = "https://github.com/chromotron"

[menu]
  [[menu.header]]
    name = "posts"
    weight = 1
    url = "/posts"

  [[menu.header]]
    name = "about"
    weight = 0
    url = "/about"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[related]
  toLower = true

[[related.indices]]
  name = 'series'
  weight = 100
  includeNewer = true
