baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'nightfall'

[params]
author = "Daniel Harrer"
user = "chromotron"
hostname = "github.io"

[[params.social]]
key = 0
name = "github"
url = "https://github.com/chromotron"